from __future__ import annotations

from collections import Counter
from typing import Any

from .models import Finding


def summarize(findings: list[Finding], files_scanned: int) -> dict[str, Any]:
    severity_counts = Counter(finding.severity for finding in findings)
    category_counts = Counter(finding.category for finding in findings)
    score = _risk_score(severity_counts)
    return {
        "files_scanned": files_scanned,
        "total_findings": len(findings),
        "severity_counts": dict(severity_counts),
        "category_counts": dict(category_counts),
        "risk_score": score,
        "risk_label": _risk_label(score),
    }


def issue_body(findings: list[Finding], patch: str) -> str:
    lines = [
        "## AI vulnerability audit report",
        "",
        f"Total findings: {len(findings)}",
        "",
    ]
    for finding in findings[:30]:
        lines.extend(
            [
                f"### [{finding.severity.upper()}] {finding.title}",
                f"- File: `{finding.file_path}:{finding.line}`",
                f"- Category: {finding.category}",
                f"- CWE: {finding.cwe or 'N/A'}",
                f"- Evidence: `{finding.evidence}`",
                f"- Recommendation: {finding.recommendation}",
                "",
            ]
        )
    if patch:
        lines.extend(["## Proposed patch", "", "```diff", patch[:60000], "```"])
    return "\n".join(lines)


def pull_request_body(findings: list[Finding], patch: str) -> str:
    fixed = [finding for finding in findings if finding.fixable]
    lines = [
        "## Summary",
        "",
        "- Applies safe automatic fixes generated by the AI vulnerability audit assistant.",
        f"- Fixable findings included in this PR: {len(fixed)}",
        f"- Total findings reported by the audit: {len(findings)}",
        "",
        "## Security notes",
        "",
    ]
    for finding in findings[:15]:
        marker = "fixed" if finding.fixable else "manual review"
        lines.append(f"- {marker}: `{finding.file_path}:{finding.line}` {finding.title}")
    if patch:
        lines.extend(["", "## Diff preview", "", "```diff", patch[:30000], "```"])
    return "\n".join(lines)


def _risk_score(severity_counts: Counter[str]) -> int:
    raw = (
        severity_counts.get("critical", 0) * 25
        + severity_counts.get("high", 0) * 15
        + severity_counts.get("medium", 0) * 8
        + severity_counts.get("low", 0) * 3
    )
    return min(100, raw)


def _risk_label(score: int) -> str:
    if score >= 75:
        return "critical"
    if score >= 45:
        return "high"
    if score >= 20:
        return "medium"
    if score > 0:
        return "low"
    return "clean"
